# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://davidlj95.com/meraki
title: Meraki International Folk Festival
email: info@merakibcn2018.com
author: dilexdesign &amp; davidlj95
repository: davidlj95/meraki
permalink: none
